OLED_ENABLE = yes
OLED_DRIVER = ssd1306   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
WPM_ENABLE = yes # Enable words per minute calculation
EXTRAFLAGS += -flto
CONSOLE_ENABLE = no
SLEEP_LED_ENABLE = yes
TERMINAL_ENABLE = no
MOUSEKEY_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
